# Generated by Django 4.2.10 on 2024-04-14 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0005_alter_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='step',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
