# Generated by Django 4.2.10 on 2024-04-19 19:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_recommendation_step_recommendation_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='triggers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('', 'No Triggers'), ('Animal Harm / Death', 'Animal Harm / Death'), ('Child Abuse', 'Child Abuse'), ('Drug Usage / Abuse', 'Drug Usage / Abuse'), ('Abuse and Manipulation (including sexual)', 'Abuse and Manipulation (including sexual)'), ('Violence', 'Violence'), ('Excessive Violence', 'Excessive Violence'), ('Human Death', 'Human Death'), ('Bodily Functions', 'Bodily Functions'), ('LGBT Issues & Problematic Depictions', 'LGBT Issues & Problematic Depictions'), ('Depiction of Medical Issues: Diseases and Phobias', 'Depiction of Medical Issues: Diseases and Phobias'), ('Potentially Harmful Filmmaking (flashing lights, shaky cam, etc.)', 'Potentially Harmful Filmmaking (flashing lights, shaky cam, etc.)'), ('Pregnancy Issues', 'Pregnancy Issues'), ('Sexual Content', 'Sexual Content'), ('Bigotry', 'Bigotry'), ('Potentially Scary Animals', 'Potentially Scary Animals'), ("there's an alligator/crocodile", "There's an Alligator/Crocodile"), ("someone's mouth is covered", "Someone's Mouth Is Covered"), ("there's shaving/cutting", "There's Shaving/Cutting"), ('Someone becomes unconscious', 'Someone Becomes Unconscious'), ('someone disabled played by able-bodied', 'Someone Disabled Played by Able-Bodied'), ('there are jumpscares', 'There Are Jumpscares'), ('there are clowns', 'There Are Clowns'), ('someone is possessed', 'Someone Is Possessed'), ("there's ghosts", "There's Ghosts"), ('there are razors', 'There Are Razors'), ('there are 9/11 depictions', 'There Are 9/11 Depictions'), ('there is copaganda', 'There Is Copaganda'), ("there's incarceration", "There's Incarceration"), ('reality is unstable or unhinged', 'Reality Is Unstable or Unhinged'), ("there's screaming", "There's Screaming"), ("there's fat jokes", "There's Fat Jokes"), ("there's ableist language or behavior", "There's Ableist Language or Behavior"), ("there's a large age gap", "There's a Large Age Gap"), ("there's demons or Hell", "There's Demons or Hell"), ('religion is discussed', 'Religion Is Discussed'), ('Santa (et al) is spoiled', 'Santa (et al) Is Spoiled')], max_length=100), blank=True, null=True, size=None),
        ),
    ]
