# Generated by Django 4.2.10 on 2024-04-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_alter_recommendation_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='runtime_span',
            field=models.CharField(blank=True, choices=[('0-90', '90 or less'), ('90-120', '90-120'), ('120-150', '120-150'), ('150-900', '150 or more')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='step',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='year_span',
            field=models.CharField(blank=True, choices=[('1900-1960', '1960 and before'), ('1960-1979', '1960-1979'), ('1980-1999', '1980-1999'), ('2000-2024', '2000 and after')], max_length=9, null=True),
        ),
    ]
