# Generated by Django 4.2.10 on 2024-05-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0011_movie_ddd_id_movie_group_lens_id_movie_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default='tt0000000'),
        ),
    ]
